language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install

script: phpunit --configuration phpunit.xml
